Update 1000mek_baika_extreme.js
Valine3gDev/1000x-mekanism pull request #20
Opened 2024-12-27 11:10 UTC by nekorobi-0

無駄が多かったので7割ぐらい書き直しました。

2024-12-27 12:04 UTC, Meatwo310 commented
コードがつめつめで見づらかったので各所に改行と空白を加えてみました
https://gist.github.com/Meatwo310/6be66b1c2f9df101cb1000257cfcdb1e

とはいえ変更前のコードがそのような書き方なのであまり気にするものではないかも

2024-12-27 12:10 UTC, Meatwo310 commented on kubejs/server_scripts/1000mek_baika_extreme.js
> +    }
各値(`output_multiplier`, `input_multiplier`, `processing_type`, `item_name_override`)について、それぞれどんな役割を果たしていて、変更するとどうなるのかなど、コメントまたはJSDocによる説明を設けるのが好ましいと思います

2024-12-28 04:17 UTC, HardSmoothy commented
私が書いてたコードは増築に増築を重ねてる状態だったんで簡略化していただけるのはとてもありがたいです

2024-12-28 04:22 UTC, HardSmoothy commented on kubejs/server_scripts/1000mek_energycube.js
ここはあまりまとめる利点が感じられないかも...

2024-12-28 04:30 UTC, HardSmoothy requested changes

2024-12-28 04:30 UTC, HardSmoothy commented on kubejs/server_scripts/1000mek_baika_extreme.js
> +        "fluorite":      { "ore_multiplier": 3, "output_multiplier": [6, 4, 8], "processing_type": [0, 1], "item_name_override": "mekanism:fluorite_gem" },
元のコードのミスです...
正しくは2500mB固定でなく、[1]==0の時と同様Math.floor(125*multiplier)*20です。
修正してもらえると嬉しいです

2024-12-28 04:30 UTC, HardSmoothy commented on kubejs/server_scripts/1000mek_baika_extreme.js
> +        "fluorite":      { "ore_multiplier": 3, "output_multiplier": [6, 4, 8], "processing_type": [0, 1], "item_name_override": "mekanism:fluorite_gem" },
あとできればore_multiplierは鉱石側につけてほしいです。
鉱石ごとで倍率違うというのは今回はありませんが、想定としてはあったので。

2024-12-28 20:04 UTC, HardSmoothy approved these changes

2024-12-29 05:36 UTC, Meatwo310 requested changes
修正すべき箇所がいくつかあります:
- コメントやメッセージなどの説明不足
- タイポの修正
- コードのフォーマット/整理

詳細は各コメントを参照してください。

2024-12-29 05:36 UTC, Meatwo310 commented on kubejs/server_scripts/1000mek_wind_gene.js
> +    let multipliers = [2, 8, 32, 128, 512, 2048, 8192, 32768, 131072, 532480]
末尾の値だけ周期的でないことをわかりやすくします。
ついでに再代入を防ぐため`let`から`const`に変更します。
```suggestion
    const multipliers = [2, 8, 32, 128, 512, 2048, 8192, 32768, 131072, 131072 * 4 + 8192]
```

2024-12-29 05:36 UTC, Meatwo310 commented on kubejs/server_scripts/1000mek_wind_gene.js
> +    }
無理に三項演算子を使わず中間の変数を用意することで、式のコピペをなくして構造を整理します。
```suggestion
    function addWindGeneratorRecipe(result_multipliers, item1, item2) {
        const recipeId = `compactmekanismmachines:compressed_wind_generator_x${result_multipliers}`
        const windGenPreviousMultiplier = multipliers[multipliers.indexOf(result_multipliers) - 1]

        const shape = []
        const ingredients = {
            H: item1,
            W: `compactmekanismmachines:compressed_wind_generator_x${windGenPreviousMultiplier}`
        }
        if (item2 == undefined) {
            shape.push(
                ' W ',
                'WHW',
                ' W '
            )
        } else {
            shape.push(
                'SWS',
                'WHW',
                'SWS'
            )
            ingredients["S"] = item2
        }

        event.shaped(recipeId, shape, ingredients)
    }
```

2024-12-29 05:36 UTC, Meatwo310 commented on kubejs/server_scripts/1000mek_wind_gene.js
> +    addWindGeneratorRecipe(532480,'compactmekanismmachines:compressed_wind_generator_x8192')
値のハードコーディングを避け、代わりにmultipliersの値を使用するよう変更します。
```suggestion
    addWindGeneratorRecipe(multipliers[1], 'mekanism:alloy_infused')
    addWindGeneratorRecipe(multipliers[2], 'mekanism:steel_casing')
    addWindGeneratorRecipe(multipliers[3], 'mekanism:basic_control_circuit', 'mekanism:fuelwood_heater')
    addWindGeneratorRecipe(multipliers[4], 'mekanism:module_base', 'mekanism:module_base')
    addWindGeneratorRecipe(multipliers[5], 'mekanism:dynamic_valve', 'mekanism:seismic_vibrator')
    addWindGeneratorRecipe(multipliers[6], 'megacells:cell_component_1m', 'mekanism:thermal_evaporation_valve')
    addWindGeneratorRecipe(multipliers[7], 'megacells:cell_component_4m', 'mekanism:sps_casing')
    addWindGeneratorRecipe(multipliers[8], 'mekaevolution:absolute_energy_cube')
    addWindGeneratorRecipe(multipliers[9], 'compactmekanismmachines:compressed_wind_generator_x8192')
```

2024-12-30 09:36 UTC, Meatwo310 approved these changes

2024-12-30 09:36 UTC, Meatwo310 commented
概ね修正していただいたのでパスします

いくつか気になる箇所が残っていますので、余力があれば修正していただけると助かります
- 
- https://github.com/Valine3gDev/1000x-mekanism/pull/20#discussion_r1899059221

2024-12-30 09:50 UTC, Meatwo310 commented
#23 との競合が発生していますがどう対処しましょう？
ケルタスクォーツ周りのバグがこのPRで既に治っているなら、このPR側の変更をそのまま通します

https://github.com/Valine3gDev/1000x-mekanism/pull/20/conflicts

2024-12-30 12:48 UTC, nekorobi-0 commented
もともとのコードでcertusのsuperoresの処理レシピが追加されてないわけですが、当該PRでも追加されてなさそうなんで、あのPRで何をしたいのがいまいちわかっていない。certusを処理できない状態は継続してるわけで、その上であそこのコードを変更する必要性がいまいちわかっていないのです。要するにあのPRがなぜ出されたのかを私は理解できていない。

2024-12-30 15:11 UTC, HardSmoothy commented
> #23 との競合が発生していますがどう対処しましょう？ ケルタスクォーツ周りのバグがこのPRで既に治っているなら、このPR側の変更をそのまま通します
> 
> https://github.com/Valine3gDev/1000x-mekanism/pull/20/conflicts

#20 で上書きしてください
ほかのレシピの修正がメインなので

2024-12-30 16:27 UTC, starMaylight approved these changes

2024-12-30 18:19 UTC, merged